/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndresSebastian
 */
public class Empleados extends javax.swing.JInternalFrame {
interfaces.VerificarCedula c = new interfaces.VerificarCedula();
    DefaultTableModel model;
    SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
    private String id;
    private String descripcion;
    /**
     * Creates new form Empleados
     */
    public Empleados() throws ParseException {
        initComponents();
        key = "92AE31A79FEEB2A3"; //llave
        iv = "0123456789ABCDEF"; // vector de inicialización
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String key,iv;
    public void cargarDatos(){
         tbEmpleados.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (tbEmpleados.getSelectedRow() != -1) { 
                    int fila = tbEmpleados.getSelectedRow();
                    txtCedula.setText(tbEmpleados.getValueAt(fila, 0).toString());
                    txtNombre.setText(tbEmpleados.getValueAt(fila, 1).toString().concat(" ").concat(tbEmpleados.getValueAt(fila, 2).toString()));
                    txtApellido.setText(tbEmpleados.getValueAt(fila, 3).toString().concat(" ").concat(tbEmpleados.getValueAt(fila, 4).toString()));
                    cbCargo.setSelectedItem(tbEmpleados.getValueAt(fila, 5).toString());
                    try {
                        txtFecha.setDate(f.parse(tbEmpleados.getValueAt(fila, 6).toString()));
                    } catch (ParseException ex) {
                        Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    txtDireccion.setText(tbEmpleados.getValueAt(fila, 7).toString());
                    txtTelefono.setText(tbEmpleados.getValueAt(fila, 8).toString());
                    txtMail.setText(tbEmpleados.getValueAt(fila, 9).toString());
                    cbEstCiv.setSelectedItem(tbEmpleados.getValueAt(fila, 10).toString());
                    cbGenero.setSelectedItem(tbEmpleados.getValueAt(fila, 11).toString());
                    ///
                    try {
                        txtClave.setText(interfaces.Metodos.decrypt(key, iv,tbEmpleados.getValueAt(fila, 12).toString()));
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }
                    ////
                    txtNombre.setEnabled(true);
                    txtApellido.setEnabled(true);
                    cbCargo.setEnabled(true);
                    txtFecha.setEnabled(true);
                    txtDireccion.setEnabled(true);
                    txtTelefono.setEnabled(true);
                    txtMail.setEnabled(true);
                    cbEstCiv.setEnabled(true);
                    cbGenero.setEnabled(true);
                    txtClave.setEnabled(true);
                    btActualizar.setEnabled(true);
                    btEliminar.setEnabled(true);
                    btGuardarU.setEnabled(false);
                }
            }
        });
    }
    
   public void bloquearcampos() {
        txtCedula.setEnabled(false);
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        cbCargo.setEnabled(false);
        txtFecha.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtMail.setEnabled(false);
        cbEstCiv.setEnabled(false);
        cbGenero.setEnabled(false);
        txtClave.setEnabled(false);
        btGuardarU.setEnabled(false);
        btActualizar.setEnabled(false);
        btEliminar.setEnabled(false);
        btCancelar.setEnabled(false);
    } 
   
   public void desbloquearcampos() {
        txtCedula.setEnabled(true);
        txtNombre.setEnabled(true);
        txtApellido.setEnabled(true);
        cbCargo.setEnabled(true);
        txtFecha.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtMail.setEnabled(true);
        cbEstCiv.setEnabled(true);
        cbGenero.setEnabled(true);
        txtClave.setEnabled(true);
        btGuardarU.setEnabled(true);
        btActualizar.setEnabled(true);
        btEliminar.setEnabled(true);
        btCancelar.setEnabled(true);
     }
   
   
   public void limpiar() {
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtFecha.setDate(null);
        cbCargo.setSelectedItem(null);
        cbEstCiv.setSelectedItem(null);
        cbGenero.setSelectedItem(null);
        txtMail.setText("");
        txtClave.setText("");
    }
   
   public void controlSoloNumeros(java.awt.event.KeyEvent evt) {
        int limite = 10;
        char c = evt.getKeyChar(); //Obtiene caracteres desde teclado, coge la tecla que digito Caracter por caracter
        if ((c < '0' || c > '9') && (c != '.'))//Valida que el caracter solo este entre 0 y 9, ademas acepta el punto
        {
            evt.consume(); //Metodo consume.- Que las teclas que presione fuera de rango no se permitan escribir
        }
        if (txtTelefono.getText().length() == limite) //Valida el numero de caracteres a ingresar
        {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR); //Borra caracteres fueras del limite
        }
    }
   
    public void controlSoloLetras(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }
    
    
     public void controlDireccion(java.awt.event.KeyEvent evt) {
           char c=evt.getKeyChar();
            if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && c != '-') {
                evt.consume();
            }
       }
     
      public void cargarComboEstadoCivil() {
        String[] Nombre, Apellido;
        try {
            String sql = "";
            sql = "select * from cargos";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                id = rs.getString("nom_car");
                descripcion = rs.getString("suel_emp");
                cbCargo.addItem(id);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar el combo");
        }
      }
     
     public void cargarTablaEmpleados(String Dato) {
       // Conexion cc=new Conexion();
       // Connection cn = cc.conectar();
        String[] titulos = {"CEDULA", "NOMBRE 1", "NOMBRE 2", "APELLIDO 1", "APELLIDO 2", "CARGO", "FECHA", "DIRECCIÓN", "TELEFONO", "E_MAIL", "ESTADO CIVIL", "GENERO","CLAVE"};
        String[] registros = new String[13]; 
        String suel;
        String sql;
        sql = "Select e.*, c.suel_emp from empleados e,cargos c where e.car_emp=c.nom_car AND e.ci_emp  LIKE '" + Dato + "%'";
        model = new DefaultTableModel(null, titulos);
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("ci_emp");
                registros[1] = rs.getString("nom1_emp");
                registros[2] = rs.getString("nom2_emp");
                registros[3] = rs.getString("ape1_emp");
                registros[4] = rs.getString("ape2_emp");
                registros[5] = rs.getString("car_emp");
                registros[6] = rs.getString("fec_nac_emp");
                registros[7] = rs.getString("dir_emp");
                registros[8] = rs.getString("tel_emp");
                registros[9] = rs.getString("e_mail_emp");
                registros[10] = rs.getString("est_civ_emp");
                registros[11] = rs.getString("genero");
                registros[12] = rs.getString("clave_emp");
                model.addRow(registros);
                tbEmpleados.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La tabla Empleados tiene problemas al cargarse\n" + e);
        }
    }
     private String camposVacios() {
        String vac = "";
        if (txtCedula.getText().isEmpty()) {
            vac = vac.concat("Cedula\n");
            txtCedula.requestFocus();
        }

        if (txtNombre.getText().isEmpty()) {
            vac = vac.concat("Nombre\n");
            txtNombre.requestFocus();
        }

        if (txtApellido.getText().isEmpty()) {
            vac = vac.concat("Apellido\n");
            txtApellido.requestFocus();
        }
        if (cbCargo.getSelectedItem() == null) {
            vac = vac.concat("Cargo\n");
//            cbCargo.requestFocus();
        }
        if (txtFecha.getDate() == null) {
            vac = vac.concat("Fecha de Nacimiento\n");
//            cbFecha.requestFocus();
        }
        if (txtDireccion.getText().isEmpty()) {
            vac = vac.concat("Direccion\n");
//            cbFecha.requestFocus();
        }
        if (cbEstCiv.getSelectedItem() == null) {
            vac = vac.concat("EstadoCivil\n");
//            cbCargo.requestFocus();
        }
        if (cbGenero.getSelectedItem() == null) {
            vac = vac.concat("Genero\n");
//            cbCargo.requestFocus();
        }
        if (txtClave.getText().isEmpty()) {
            vac = vac.concat("Clave\n");
//            txtClave.requestFocus();
        }

        return vac;
    }
     
      public void insertar(boolean b) {
        //Conexion cc=new Conexion();
       // Connection cn = cc.conectar();
        if (b == true) {
            PreparedStatement pst;
            String fecha,passen=null;
            String sql;
            String suel;
            String[] Nombre, Apellido;
            Nombre = txtNombre.getText().split(" ");
            Apellido = txtApellido.getText().split(" ");
            fecha = f.format(txtFecha.getDate());
            String password=txtClave.getText();
            ////
            try {
                passen=Metodos.encrypt(key, iv, password);
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, ex);
            }
            ////
            JOptionPane.showMessageDialog(null, passen);
            try {
                pst = cn.prepareStatement("INSERT INTO empleados(ci_emp, nom1_emp, nom2_emp, ape1_emp,ape2_emp, car_emp, fec_nac_emp, dir_emp, tel_emp,"
                        + " e_mail_emp, est_civ_emp, genero,clave_emp)"
                        + " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)");

                pst.setString(1, txtCedula.getText().toString());
                pst.setString(2, Nombre[0]);
                pst.setString(3, Nombre[1]);
                pst.setString(4, Apellido[0]);
                pst.setString(5, Apellido[1]);
                pst.setString(6, cbCargo.getSelectedItem().toString());
                pst.setString(7, fecha);
                pst.setString(8, txtDireccion.getText().toString());
                pst.setString(9, txtTelefono.getText().toString());
                pst.setString(10, txtMail.getText().toString());
                pst.setString(11, cbEstCiv.getSelectedItem().toString());
                pst.setString(12, cbGenero.getSelectedItem().toString());
                pst.setString(13, passen);
                int i = pst.executeUpdate();
                if (i > 0) {
                    cargarTablaEmpleados("");
                    JOptionPane.showMessageDialog(null, "EL EMPLEADO HA SIDO REGISTRADO");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No se ha podido guardar \n" + e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese datos en los siguientes campos:\n" + camposVacios());
        }
    }
     public void actualizarEmpleado() {
             String sql, dir,passen=null;
        String[] Nombre, Apellido;
         //  Conexion cc=new Conexion();
       // Connection cn = cc.conectar();
            Nombre = txtNombre.getText().split(" ");
            Apellido = txtApellido.getText().split(" ");
            String password = txtClave.getText();
           ////
            try {
                passen=interfaces.Metodos.encrypt(key, iv, password);
            } catch (Exception ex) {
               
            }
             sql = "update empleados set nom1_emp ='" + Nombre[0] 
                + "',nom2_emp='" + Nombre[1] 
                + "',ape1_emp='" + Apellido[0] 
                + "',ape2_emp='" + Apellido[1] 
                + "',car_emp='" + cbCargo.getSelectedItem()
                + "',fec_nac_emp='"+f.format(txtFecha.getDate())
                + "',dir_emp='" + txtDireccion.getText() 
                + "',tel_emp='" + txtTelefono.getText() 
                + "',e_mail_emp='" + txtMail.getText() 
                + "',est_civ_emp='" + cbEstCiv.getSelectedItem() 
                + "',genero='" + cbGenero.getSelectedItem() 
                + "',clave_emp='" + passen 
                + "'where ci_emp='" + txtCedula.getText() + "'";
        try {
            PreparedStatement psd = cn.prepareStatement(sql);
            int n = psd.executeUpdate();
            if (n > 0) {
                //JOptionPane.showMessageDialog(this, "Se actualizo correctamente");
                cargarTablaEmpleados("");
                limpiar();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar" + ex);
        }
    }
      private boolean control() {
        boolean ver = true;
        if (txtCedula.getText().isEmpty() || txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty()
                || txtDireccion.getText().isEmpty() || cbCargo.getSelectedItem() == null || cbEstCiv.getSelectedItem() == null
                || cbGenero.getSelectedItem() == null || txtFecha.getDate() == null || txtClave.getText().isEmpty()) {
            ver = false;
        }
        return ver;
    }
      
      
      private boolean control1() {
           boolean ver = true;
        if (txtCedula.getText().isEmpty() || txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty()
                || txtDireccion.getText().isEmpty() || cbCargo.getSelectedItem() == null || cbEstCiv.getSelectedItem() == null
                || cbGenero.getSelectedItem() == null || txtFecha.getDate() == null ) {
            ver = false;
        }
        return ver;
    }
      
      public void borrar() {
       // Conexion cc=new Conexion();
        //Connection cn = cc.conectar();
        if (JOptionPane.showConfirmDialog(new JInternalFrame(), "Esta seguro que desea eliminar el dato", "Borra registro", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            String sql = "";
            sql = "delete from empleados where ci_emp ='" + txtCedula.getText() + "'";
            try {
                PreparedStatement psd = cn.prepareStatement(sql);
                int n = psd.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(null, "Se borro el registro");
                    cargarTablaEmpleados("");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Nose pudo borrar el registro");
            }
        }
    }
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        cbCargo = new javax.swing.JComboBox<>();
        Mostrar = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtFecha = new com.toedter.calendar.JDateChooser();
        cbEstCiv = new javax.swing.JComboBox<>();
        cbGenero = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarCed = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleados = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btEliminar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        btGuardarU = new javax.swing.JButton();
        btNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EMPLEADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("NOMBRE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("APELLIDO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("CEDULA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("CARGO");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("CLAVE");

        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoKeyReleased(evt);
            }
        });

        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });

        Mostrar.setText("Mostrar Clave");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Mostrar)
                    .addComponent(txtCedula)
                    .addComponent(txtClave)
                    .addComponent(txtApellido)
                    .addComponent(txtNombre)
                    .addComponent(cbCargo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 240, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mostrar)
                .addGap(12, 12, 12))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("FECHA DE NACIMIENTO");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("DIRECCIÓN");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("E_MAIL");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("TELÉFONO");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("ESTADO CIVIL");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("GENERO");

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMailKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccion)
                    .addComponent(txtTelefono)
                    .addComponent(txtMail)
                    .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(cbEstCiv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbEstCiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSCAR EMPLEADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("CEDULA");

        txtBuscarCed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCedActionPerformed(evt);
            }
        });
        txtBuscarCed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCedKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarCedKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(txtBuscarCed, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscarCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EMPLEADOS EXISTENTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        tbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbEmpleados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btEliminar.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BASU.png"))); // NOI18N
        btEliminar.setText("ELIMINAR");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1467088618_Cancel.png"))); // NOI18N
        btCancelar.setText("CANCELAR");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btActualizar.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1 (1).png"))); // NOI18N
        btActualizar.setText("ACTUALIZAR");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        btGuardarU.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btGuardarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/guardar.png"))); // NOI18N
        btGuardarU.setText("GUARDAR");
        btGuardarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarUActionPerformed(evt);
            }
        });

        btNuevo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/EMPLO.png"))); // NOI18N
        btNuevo.setText("NUEVO");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGuardarU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGuardarU, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
 c.controlCaracteres(evt);
 // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
c.validacion(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaFocusLost

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
     limpiar();
    txtBuscarCed.setText("");
    desbloquearcampos();
    btActualizar.setEnabled(false);
    btEliminar.setEnabled(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_btNuevoActionPerformed

    private void btGuardarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarUActionPerformed
       insertar(control());
    cargarTablaEmpleados("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarUActionPerformed

    private void txtBuscarCedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCedActionPerformed

    private void txtBuscarCedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCedKeyReleased
insertar(control());
    cargarTablaEmpleados("");
    // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCedKeyReleased

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
actualizarEmpleado();
// TODO add your handling code here:
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
 borrar();
    limpiar();
    // TODO add your handling code here:
    }//GEN-LAST:event_btEliminarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
  controlSoloLetras(evt);
  // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
txtNombre.setText((txtNombre.getText().toUpperCase()));
// TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyReleased
 txtApellido.setText((txtApellido.getText().toUpperCase()));
 // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoKeyReleased

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
controlSoloLetras(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
controlSoloNumeros(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
controlDireccion(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtMailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMailKeyReleased
 txtMail.setText((txtMail.getText().toLowerCase()));
 // TODO add your handling code here:
    }//GEN-LAST:event_txtMailKeyReleased

    private void txtBuscarCedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCedKeyTyped
int limite = 10;
    char c = evt.getKeyChar(); //Obtiene caracteres desde teclado, coge la tecla que digito Caracter por caracter
    if ((c < '0' || c > '9') && (c != '.'))//Valida que el caracter solo este entre 0 y 9, ademas acepta el punto
    {
        evt.consume(); //Metodo consume.- Que las teclas que presione fuera de rango no se permitan escribir
    }
    if (txtBuscarCed.getText().length() == limite) //Valida el numero de caracteres a ingresar
    {
        evt.setKeyChar((char) KeyEvent.VK_CLEAR); //Borra caracteres fueras del limite
    }      
    // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCedKeyTyped

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
 limpiar();
 // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
 if (Mostrar.isSelected()) {
            txtClave.setEchoChar((char) 0);
        } else {
            txtClave.setEchoChar('*');
        }
 // TODO add your handling code here:
    }//GEN-LAST:event_MostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Empleados().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Mostrar;
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEliminar;
    public static javax.swing.JButton btGuardarU;
    private javax.swing.JButton btNuevo;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JComboBox<String> cbEstCiv;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEmpleados;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscarCed;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDireccion;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
interfaces.Conexion cc=new interfaces.Conexion();
     Connection cn = cc.conectar();
}
